package com.java.app.utility;

import java.util.HashMap;
import java.util.Map;
import java.util.Optional;

import org.springframework.stereotype.Component;

@Component
public class ColorUtil {
	
	private static final Map<String, String> COLOR_TABLE = new HashMap<>();
	
	static {
		COLOR_TABLE.put("black","000000");
		COLOR_TABLE.put("white","FFFFFF");
		COLOR_TABLE.put("red","FF0000");
		COLOR_TABLE.put("lime","00FF00");
		COLOR_TABLE.put("blue","0000FF");
		COLOR_TABLE.put("yellow","FFFF00");
		COLOR_TABLE.put("cyan","00FFFF");
		COLOR_TABLE.put("magenta","FF00FF");
		COLOR_TABLE.put("aqua","00FFFF");
		COLOR_TABLE.put("fuchsia","FF00FF");
		COLOR_TABLE.put("silver","C0C0C0");
		COLOR_TABLE.put("gray","808080");
		COLOR_TABLE.put("maroon","800000");
		COLOR_TABLE.put("olive","808000");
		COLOR_TABLE.put("green","008000");
		COLOR_TABLE.put("purple","800080");
		COLOR_TABLE.put("teal","008080");
		COLOR_TABLE.put("navy","000080");
		COLOR_TABLE.put("maroon","800000");
		COLOR_TABLE.put("dark red","8B0000");
		COLOR_TABLE.put("brown","A52A2A");
		COLOR_TABLE.put("firebrick","B22222");
		COLOR_TABLE.put("crimson","DC143C");
		COLOR_TABLE.put("red","FF0000");
		COLOR_TABLE.put("tomato","FF6347");
		COLOR_TABLE.put("coral","FF7F50");
		COLOR_TABLE.put("indian red","CD5C5C");
		COLOR_TABLE.put("light coral","F08080");
		COLOR_TABLE.put("dark salmon","E9967A");
		COLOR_TABLE.put("salmon","FA8072");
		COLOR_TABLE.put("light salmon","FFA07A");
		COLOR_TABLE.put("orange red","FF4500");
		COLOR_TABLE.put("dark orange","FF8C00");
		COLOR_TABLE.put("orange","FFA500");
		COLOR_TABLE.put("gold","FFD700");
		COLOR_TABLE.put("dark golden rod","B8860B");
		COLOR_TABLE.put("golden rod","DAA520");
		COLOR_TABLE.put("pale golden rod","EEE8AA");
		COLOR_TABLE.put("dark khaki","BDB76B");
		COLOR_TABLE.put("khaki","F0E68C");
		COLOR_TABLE.put("olive","808000");
		COLOR_TABLE.put("yellow","FFFF00");
		COLOR_TABLE.put("yellow green","9ACD32");
		COLOR_TABLE.put("dark olive green","556B2F");
		COLOR_TABLE.put("olive drab","6B8E23");
		COLOR_TABLE.put("lawn green","7CFC00");
		COLOR_TABLE.put("chart reuse","7FFF00");
		COLOR_TABLE.put("green yellow","ADFF2F");
		COLOR_TABLE.put("dark green","006400");
		COLOR_TABLE.put("green","008000");
		COLOR_TABLE.put("forest green","228B22");
		COLOR_TABLE.put("lime","00FF00");
		COLOR_TABLE.put("lime green","32CD32");
		COLOR_TABLE.put("light green","90EE90");
		COLOR_TABLE.put("pale green","98FB98");
		COLOR_TABLE.put("dark sea green","8FBC8F");
		COLOR_TABLE.put("medium spring green","00FA9A");
		COLOR_TABLE.put("spring green","00FF7F");
		COLOR_TABLE.put("sea green","2E8B57");
		COLOR_TABLE.put("medium aqua marine","66CDAA");
		COLOR_TABLE.put("medium sea green","3CB371");
		COLOR_TABLE.put("light sea green","20B2AA");
		COLOR_TABLE.put("dark slate gray","2F4F4F");
		COLOR_TABLE.put("teal","008080");
		COLOR_TABLE.put("dark cyan","008B8B");
		COLOR_TABLE.put("aqua","00FFFF");
		COLOR_TABLE.put("cyan","00FFFF");
		COLOR_TABLE.put("light cyan","E0FFFF");
		COLOR_TABLE.put("dark turquoise","00CED1");
		COLOR_TABLE.put("turquoise","40E0D0");
		COLOR_TABLE.put("medium turquoise","48D1CC");
		COLOR_TABLE.put("pale turquoise","AFEEEE");
		COLOR_TABLE.put("aqua marine","7FFFD4");
		COLOR_TABLE.put("powder blue","B0E0E6");
		COLOR_TABLE.put("cadet blue","5F9EA0");
		COLOR_TABLE.put("steel blue","4682B4");
		COLOR_TABLE.put("corn flower blue","6495ED");
		COLOR_TABLE.put("deep sky blue","00BFFF");
		COLOR_TABLE.put("dodger blue","1E90FF");
		COLOR_TABLE.put("light blue","ADD8E6");
		COLOR_TABLE.put("sky blue","87CEEB");
		COLOR_TABLE.put("light sky blue","87CEFA");
		COLOR_TABLE.put("midnight blue","191970");
		COLOR_TABLE.put("navy","000080");
		COLOR_TABLE.put("dark blue","00008B");
		COLOR_TABLE.put("medium blue","0000CD");
		COLOR_TABLE.put("blue","0000FF");
		COLOR_TABLE.put("royal blue","4169E1");
		COLOR_TABLE.put("blue violet","8A2BE2");
		COLOR_TABLE.put("indigo","4B0082");
		COLOR_TABLE.put("dark slate blue","483D8B");
		COLOR_TABLE.put("slate blue","6A5ACD");
		COLOR_TABLE.put("medium slate blue","7B68EE");
		COLOR_TABLE.put("medium purple","9370DB");
		COLOR_TABLE.put("dark magenta","8B008B");
		COLOR_TABLE.put("dark violet","9400D3");
		COLOR_TABLE.put("dark orchid","9932CC");
		COLOR_TABLE.put("medium orchid","BA55D3");
		COLOR_TABLE.put("purple","800080");
		COLOR_TABLE.put("thistle","D8BFD8");
		COLOR_TABLE.put("plum","DDA0DD");
		COLOR_TABLE.put("violet","EE82EE");
		COLOR_TABLE.put("magenta / fuchsia","FF00FF");
		COLOR_TABLE.put("orchid","DA70D6");
		COLOR_TABLE.put("medium violet red","C71585");
		COLOR_TABLE.put("pale violet red","DB7093");
		COLOR_TABLE.put("deep pink","FF1493");
		COLOR_TABLE.put("hot pink","FF69B4");
		COLOR_TABLE.put("light pink","FFB6C1");
		COLOR_TABLE.put("pink","FFC0CB");
		COLOR_TABLE.put("antique white","FAEBD7");
		COLOR_TABLE.put("beige","F5F5DC");
		COLOR_TABLE.put("bisque","FFE4C4");
		COLOR_TABLE.put("blanched almond","FFEBCD");
		COLOR_TABLE.put("wheat","F5DEB3");
		COLOR_TABLE.put("corn silk","FFF8DC");
		COLOR_TABLE.put("lemon chiffon","FFFACD");
		COLOR_TABLE.put("light golden rod yellow","FAFAD2");
		COLOR_TABLE.put("light yellow","FFFFE0");
		COLOR_TABLE.put("saddle brown","8B4513");
		COLOR_TABLE.put("sienna","A0522D");
		COLOR_TABLE.put("chocolate","D2691E");
		COLOR_TABLE.put("peru","CD853F");
		COLOR_TABLE.put("sandy brown","F4A460");
		COLOR_TABLE.put("burly wood","DEB887");
		COLOR_TABLE.put("tan","D2B48C");
		COLOR_TABLE.put("rosy brown","BC8F8F");
		COLOR_TABLE.put("moccasin","FFE4B5");
		COLOR_TABLE.put("navajo white","FFDEAD");
		COLOR_TABLE.put("peach puff","FFDAB9");
		COLOR_TABLE.put("misty rose","FFE4E1");
		COLOR_TABLE.put("lavender blush","FFF0F5");
		COLOR_TABLE.put("linen","FAF0E6");
		COLOR_TABLE.put("old lace","FDF5E6");
		COLOR_TABLE.put("papaya whip","FFEFD5");
		COLOR_TABLE.put("sea shell","FFF5EE");
		COLOR_TABLE.put("mint cream","F5FFFA");
		COLOR_TABLE.put("slate gray","708090");
		COLOR_TABLE.put("light slate gray","778899");
		COLOR_TABLE.put("light steel blue","B0C4DE");
		COLOR_TABLE.put("lavender","E6E6FA");
		COLOR_TABLE.put("floral white","FFFAF0");
		COLOR_TABLE.put("alice blue","F0F8FF");
		COLOR_TABLE.put("ghost white","F8F8FF");
		COLOR_TABLE.put("honeydew","F0FFF0");
		COLOR_TABLE.put("ivory","FFFFF0");
		COLOR_TABLE.put("azure","F0FFFF");
		COLOR_TABLE.put("snow","FFFAFA");
		COLOR_TABLE.put("black","000000");
		COLOR_TABLE.put("dim gray / dim grey","696969");
		COLOR_TABLE.put("gray / grey","808080");
		COLOR_TABLE.put("dark gray / dark grey","A9A9A9");
		COLOR_TABLE.put("silver","C0C0C0");
		COLOR_TABLE.put("light gray / light grey","D3D3D3");
		COLOR_TABLE.put("gainsboro","DCDCDC");
		COLOR_TABLE.put("white smoke","F5F5F5");
		COLOR_TABLE.put("white","FFFFFF");
	}
	
	public String basicToRgb(String colorName) {
		return Optional.ofNullable(COLOR_TABLE.get(colorName.toLowerCase())).orElse("");
	}
	
}
